server:
  error:
    include-stacktrace: never

spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  data-source:
    url: jdbc:mysql://localhost:3306/school-management-db?createDatabaseIfNotExist=true
    username: root
    password: password